### ISSUE TITLE
Use labels instead of container names

### ISSUE THREAD

**Issue by airtonix** [meltwater/docker-cleanup#29]
https://docs.docker.com/compose/compose-file/#labels

ie : 

``` yml
labels:
  com.janitor.ephemeral: true
  com.janitor.dependsOn: [ 'container-name', 'container-name']
```
